/**
 * Style Dictionary build.
 *
 * Reads DTCG token files from tokens/ and produces four artifacts under generated/:
 *
 *   tokens.css           :root block of --ds-* custom properties. The runtime source
 *                        of every design value.
 *   tokens.ts            the same values as typed TypeScript constants.
 *   tailwind-theme.css   a Tailwind 4 @theme block binding Tailwind's utility
 *                        namespaces to the custom properties above.
 *   font-utilities.css   Tailwind 4 @utility blocks for the COMPOSITE font tokens.
 *
 * The third is what makes `bg-surface-brand-bold` a real class, and the fourth is
 * what makes `font-body-sm-moderate` one.
 *
 * Two rules are enforced here rather than in review, because here they are the
 * difference between a class existing and not existing:
 *
 *   1. Primitives are NOT published. A colour step (`brand-500`, `neutral-100`) has
 *      no Tailwind utility at all, so a component cannot reach past the semantic
 *      layer even by accident.
 *   2. A composite font token is published as ONE utility setting all four
 *      properties together. Publishing size, weight and line-height separately is
 *      exactly what lets them drift apart at a call site.
 *
 * generated/ is not committed. Every script that needs it runs build:tokens first.
 */
import StyleDictionary from 'style-dictionary';

const PREFIX = 'ds';

const cssVarName = (token) => `--${PREFIX}-${token.path.join('-')}`;

/**
 * Groups published as Tailwind utilities, and the namespace each lands in.
 *
 * `keepGroup` is not cosmetic: three groups share the `color` namespace, so dropping
 * the group name would collapse `fg.default` and `surface.default` into a single
 * --color-default, and the second would silently win.
 */
const TAILWIND_NAMESPACES = [
  { group: 'fg', namespace: 'color', keepGroup: true },
  { group: 'surface', namespace: 'color', keepGroup: true },
  { group: 'outline', namespace: 'color', keepGroup: true },
  { group: 'radius', namespace: 'radius' },
  { group: 'shadow', namespace: 'shadow' },
  { group: 'font-size', namespace: 'text' },
  { group: 'font-weight', namespace: 'font-weight' },
  { group: 'font-family', namespace: 'font' },
  { group: 'line-height', namespace: 'leading' },
  { group: 'letter-spacing', namespace: 'tracking' },
];

/**
 * Groups that reach CSS as --ds-* variables but deliberately get NO utility.
 *
 * Each is a decision, not an omission. `chart`, `chip`, `input` and `shared` are
 * component-layer values consumed through var() by the component that owns them;
 * `motion`, `z-index` and `layout` need a name rather than a class; `font` is
 * composite and published through @utility instead; `spacing` drives Tailwind's
 * numeric scale and is handled separately below.
 */
/**
 * The spacing token Tailwind's numeric scale is derived from. Named here because the
 * key differs between token sets (`base`, `unit`, `step`) and getting it wrong is
 * invisible: Tailwind falls back to its own default and everything still renders.
 */
const SPACING_UNIT_KEY = 'unit';

const UNPUBLISHED_GROUPS = [
  'chart', 'chip', 'input', 'shared', 'motion', 'z-index', 'layout', 'font',
];

/**
 * A primitive colour step: `brand-500`, `neutral-100`, `chart-blue-300`, `black`.
 *
 * Matched by SHAPE rather than listed by name, because the palette families are
 * named after places and adding one must not need a code change to stay unpublished.
 * Getting this backwards — publishing a primitive — does not produce a wrong colour.
 * It produces a class that works, which is how a semantic layer gets bypassed.
 */
const isPrimitiveColour = (group) =>
  /^[a-z][a-z-]*-\d{2,3}$/.test(group) || group === 'black' || group === 'white';

const isComposite = (token) => {
  const v = token.$value ?? token.value;
  return v !== null && typeof v === 'object';
};

StyleDictionary.registerFormat({
  name: 'css/tokens',
  format: ({ dictionary }) => {
    // A composite token has an object value and becomes a set of utilities, not a
    // custom property. Emitting it here would write "[object Object]" into the
    // stylesheet — valid CSS, completely inert, and invisible until someone looks.
    const lines = dictionary.allTokens
      .filter((t) => !isComposite(t))
      .map((t) => `  ${cssVarName(t)}: ${t.$value ?? t.value};`);
    return [
      '/* GENERATED by style-dictionary — do not edit. Source: tokens/ */',
      ':root {',
      ...lines,
      '}',
      '',
    ].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'ts/tokens',
  format: ({ dictionary }) => {
    // JSON.stringify, not a hand-rolled quote. Font stacks contain apostrophes
    // ('Lexend Deca'), and wrapping those in single quotes produces a file that
    // looks fine and is a syntax error to compile.
    const composite = dictionary.allTokens.filter(isComposite);
    if (composite.length) {
      // With the css transform group nothing should still be an object here. If one
      // is, it would be silently omitted and a page would render an empty section —
      // which is exactly how the shadows went missing.
      throw new Error(
        `these tokens are still objects after transformation and would be dropped: ` +
          `${composite.map((t) => t.path.join('.')).join(', ')}`,
      );
    }
    const entries = dictionary.allTokens.map(
      (t) => `  ${JSON.stringify(t.path.join('.'))}: ${JSON.stringify(String(t.$value ?? t.value))},`,
    );
    return [
      '// GENERATED by style-dictionary — do not edit. Source: tokens/',
      'export const tokens = {',
      ...entries,
      '} as const;',
      '',
      'export type TokenName = keyof typeof tokens;',
      '',
    ].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'css/tailwind-theme',
  format: ({ dictionary }) => {
    const out = [];
    const unclassified = new Set();
    let publishedSpacingUnit = false;

    for (const token of dictionary.allTokens) {
      const [group, ...rest] = token.path;
      if (isComposite(token)) continue;
      if (isPrimitiveColour(group) || UNPUBLISHED_GROUPS.includes(group)) continue;

      if (group === 'spacing' && rest[0] === SPACING_UNIT_KEY) {
        // Tailwind multiplies this one to derive the whole numeric scale
        // (p-4 -> calc(var(--spacing) * 4)), so it publishes under its own name.
        out.push(`  --spacing: var(${cssVarName(token)});`);
        publishedSpacingUnit = true;
        continue;
      }
      // Every other spacing token documents a value rather than driving the scale
      // (a fractional step is already reachable as p-1.5).
      if (group === 'spacing') continue;

      const named = TAILWIND_NAMESPACES.find((n) => n.group === group);
      if (!named) {
        unclassified.add(group);
        continue;
      }
      const suffix = named.keepGroup ? token.path.join('-') : rest.join('-');
      out.push(`  --${named.namespace}-${suffix}: var(${cssVarName(token)});`);
    }

    // A token group nobody has classified is a decision waiting to be made, not a
    // value to guess a namespace for. A guessed namespace produces a class that
    // half-works, and those surface much later than a failed build.
    if (unclassified.size) {
      throw new Error(
        `token group(s) ${[...unclassified].sort().join(', ')} are neither published ` +
          `(TAILWIND_NAMESPACES) nor deliberately withheld (UNPUBLISHED_GROUPS / ` +
          `isPrimitiveColour). Classify them in sd.config.mjs.`,
      );
    }

    // Tailwind ships its own --spacing (0.25rem). If ours never publishes, the whole
    // numeric scale silently falls back to it — and because the token happens to be
    // 4px, the result is IDENTICAL until someone changes the token and nothing moves.
    // A default that agrees with you by coincidence is the hardest kind to notice.
    if (!publishedSpacingUnit) {
      throw new Error(
        `no spacing token named '${SPACING_UNIT_KEY}' was found, so --spacing was never ` +
          `published and Tailwind's own default drives p-*, gap-*, m-* and the rest. ` +
          `Rename the token or update SPACING_UNIT_KEY in sd.config.mjs.`,
      );
    }

    // A duplicate variable name is the one failure this format can produce that
    // looks completely fine: valid CSS, green build, and one of the two tokens
    // silently stops existing.
    const seen = new Map();
    for (const line of out) {
      const name = line.trim().split(':')[0];
      if (seen.has(name)) {
        throw new Error(
          `two tokens both publish '${name}':\n  ${seen.get(name).trim()}\n  ${line.trim()}\n` +
            `One would silently overwrite the other. Give one of them keepGroup, or rename it.`,
        );
      }
      seen.set(name, line);
    }

    return [
      '/* GENERATED by style-dictionary — do not edit. Source: tokens/ */',
      '@theme inline {',
      ...out,
      '}',
      '',
    ].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'css/font-utilities',
  format: ({ dictionary }) => {
    // Style Dictionary's css transform group already collapses a DTCG `typography`
    // token into the CSS `font` shorthand — "300 0.75rem/1.125rem 'Lexend Deca', ...".
    // So the utility binds the whole shorthand through one variable rather than
    // re-deriving four properties, and there is exactly one place the value lives.
    const composites = dictionary.allTokens.filter((t) => t.path[0] === 'font');

    const blocks = composites.flatMap((token) => {
      const name = token.path.join('-'); // font.body.sm.moderate -> font-body-sm-moderate
      // `font:` the shorthand, not four separate declarations. A call site that can
      // set the size without the line-height is a call site where they drift apart,
      // and binding the variable (rather than inlining the value) is what keeps the
      // utility and the token the same fact.
      return [`@utility ${name} {`, `  font: var(${cssVarName(token)});`, `}`, ''];
    });

    if (blocks.length === 0) {
      throw new Error(
        'no composite font tokens found — expected tokens/typography/font.json to ' +
          'contain $type: typography entries under a `font` group. An empty utilities ' +
          'file would leave every `font-body-*` class silently undefined.',
      );
    }

    return [
      '/* GENERATED by style-dictionary — do not edit. Source: tokens/typography/font.json */',
      '',
      ...blocks,
    ].join('\n');
  },
});

export default {
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'generated/',
      files: [
        { destination: 'tokens.css', format: 'css/tokens' },
        { destination: 'tailwind-theme.css', format: 'css/tailwind-theme' },
        { destination: 'font-utilities.css', format: 'css/font-utilities' },
      ],
    },
    ts: {
      // 'css', not 'js', deliberately. The js transform group leaves a shadow and a
      // cubic-bezier as OBJECTS, while css collapses them to the string that actually
      // ships. Building the TypeScript export from the js group therefore silently
      // dropped every shadow and easing — the token pages rendered an empty Elevation
      // section, and the Storybook build exited 0 the whole time. Same transforms as
      // the stylesheet means the two cannot disagree.
      transformGroup: 'css',
      buildPath: 'generated/',
      files: [{ destination: 'tokens.ts', format: 'ts/tokens' }],
    },
  },
};
