/**
 * Style Dictionary build for the demo design system.
 *
 * Reads DTCG token files from tokens/ and produces three artifacts under generated/:
 *
 *   tokens.css          :root block of --ds-* custom properties. The runtime source
 *                       of every design value.
 *   tokens.ts           the same values as typed TypeScript constants, for the rare
 *                       case where a value is needed in JS rather than CSS.
 *   tailwind-theme.css  a Tailwind 4 @theme block that binds Tailwind's utility
 *                       namespaces to the custom properties above.
 *
 * The last one is what makes `bg-surface-accent` a real class. Tailwind 4 derives
 * utilities from the variables declared in @theme, so a token that is not published
 * there has no utility — which is deliberate: primitives stay unpublished, and a
 * component reaching for `bg-neutral-900` finds no such class.
 *
 * generated/ is not committed. Every script that needs it runs build:tokens first.
 */
import StyleDictionary from 'style-dictionary';

const PREFIX = 'ds';

/** `fg.default` -> `--ds-fg-default` */
const cssVarName = (token) => `--${PREFIX}-${token.path.join('-')}`;

/**
 * Which token groups become Tailwind utilities, and under which namespace.
 *
 * Absence from this table is meaningful. `color.*` (the primitives) is absent, so
 * no utility exists for a raw palette step — the strict primitive -> semantic ->
 * component chain the governance skill requires is enforced here, at the point
 * where a class either exists or does not.
 */
const TAILWIND_NAMESPACES = [
  // `keepGroup` is not cosmetic. Three groups share the `color` namespace, so
  // dropping the group name collapses fg.default and surface.default into one
  // --color-default and the second silently wins. Where the namespace holds one
  // group only, the group name is dropped and `radius.sm` becomes --radius-sm.
  { group: 'fg', namespace: 'color', keepGroup: true },
  { group: 'surface', namespace: 'color', keepGroup: true },
  { group: 'border', namespace: 'color', keepGroup: true },
  { group: 'radius', namespace: 'radius' },
  { group: 'shadow', namespace: 'shadow' },
  { group: 'font-size', namespace: 'text' },
  { group: 'font-weight', namespace: 'font-weight' },
  { group: 'font-family', namespace: 'font' },
  { group: 'line-height', namespace: 'leading' },
  { group: 'letter-spacing', namespace: 'tracking' },
];

/**
 * Groups that reach CSS as --ds-* variables but get NO Tailwind utility.
 *
 * Not an oversight in each case, a decision: `palette` is the primitive layer and
 * must stay unreachable from a component; `motion`, `z-index`, `layout` and
 * `shared` are consumed through var() in a component's own styles, where the
 * value needs a name rather than a class.
 */
const UNPUBLISHED_GROUPS = ['palette', 'motion', 'z-index', 'layout', 'shared'];

StyleDictionary.registerFormat({
  name: 'css/tokens',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map(
      (t) => `  ${cssVarName(t)}: ${t.$value ?? t.value};`,
    );
    return [
      '/* GENERATED by style-dictionary — do not edit. Source: tokens/ */',
      ':root {',
      ...lines,
      '}',
      '',
    ].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'ts/tokens',
  format: ({ dictionary }) => {
    // JSON.stringify, not a hand-rolled quote. Font stacks and shadow values contain
    // apostrophes ('Lexend Deca', 'SF Mono'), and wrapping those in single quotes
    // produces a file that is valid to look at and a syntax error to compile.
    const entries = dictionary.allTokens.map(
      (t) => `  ${JSON.stringify(t.path.join('.'))}: ${JSON.stringify(String(t.$value ?? t.value))},`,
    );
    return [
      '// GENERATED by style-dictionary — do not edit. Source: tokens/',
      'export const tokens = {',
      ...entries,
      '} as const;',
      '',
      'export type TokenName = keyof typeof tokens;',
      '',
    ].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'css/tailwind-theme',
  format: ({ dictionary }) => {
    const out = [];
    for (const token of dictionary.allTokens) {
      const [group, ...rest] = token.path;

      if (UNPUBLISHED_GROUPS.includes(group)) continue;

      const named = TAILWIND_NAMESPACES.find((n) => n.group === group);
      if (named) {
        // The group name is dropped when it already IS the namespace: radius.sm
        // publishes --radius-sm, not --radius-radius-sm (which yields the class
        // `rounded-radius-sm` and reads like a typo because it is one). For a
        // renamed group — font-size -> text — the group name is dropped too, and
        // only the leaf path remains.
        const suffix = named.keepGroup ? token.path.join('-') : rest.join('-');
        out.push(`  --${named.namespace}-${suffix}: var(${cssVarName(token)});`);
        continue;
      }
      if (group === 'spacing' && rest[0] === 'base') {
        // Tailwind multiplies this one to derive the whole numeric scale
        // (p-4 -> calc(var(--spacing) * 4)), so it is published under its own name.
        out.push(`  --spacing: var(${cssVarName(token)});`);
        continue;
      }
      // Anything else is a token group nobody has decided about. Failing loudly
      // beats emitting a variable under a guessed namespace, because a guessed
      // namespace produces a class that half-works and is found much later.
      throw new Error(
        `token group '${group}' is neither published (TAILWIND_NAMESPACES) nor ` +
          `deliberately withheld (UNPUBLISHED_GROUPS). Add it to one of them in sd.config.mjs.`,
      );
    }
    // A duplicate variable name is the one failure this format can produce that
    // looks completely fine in the output: the file is valid CSS, the build is
    // green, and one of the two tokens simply stops existing. Caught here rather
    // than found later by someone wondering why a colour will not change.
    const seen = new Map();
    for (const line of out) {
      const name = line.trim().split(':')[0];
      if (seen.has(name)) {
        throw new Error(
          `two tokens both publish '${name}':\n  ${seen.get(name).trim()}\n  ${line.trim()}\n` +
            `One would silently overwrite the other. Give one of them keepGroup, or rename it.`,
        );
      }
      seen.set(name, line);
    }
    return [
      '/* GENERATED by style-dictionary — do not edit. Source: tokens/ */',
      '@theme inline {',
      ...out,
      '}',
      '',
    ].join('\n');
  },
});

export default {
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'generated/',
      files: [
        { destination: 'tokens.css', format: 'css/tokens' },
        { destination: 'tailwind-theme.css', format: 'css/tailwind-theme' },
      ],
    },
    ts: {
      transformGroup: 'js',
      buildPath: 'generated/',
      files: [{ destination: 'tokens.ts', format: 'ts/tokens' }],
    },
  },
};
