import type { Meta, StoryObj } from '@storybook/react';
import { expect, userEvent, within } from '@storybook/test';

import { Input } from './input';

/*
 * story_generation_schema: 1
 *
 * Generated by storybook-stories-generator (#6) as a projection of
 * docs/component-specs/input.md (frozen on main, PR #28) x src/components/ui/input.tsx.
 *
 * This file is FULLY OWNED by #6 and is regenerated whole. Do not hand-author a story
 * in here — it will be overwritten. A bespoke story belongs in input.custom.stories.tsx,
 * which #6 never reads or writes.
 *
 * Every story below traces to something the spec declares. There is no story for a
 * scenario the spec does not name, and no prop used that the component does not expose.
 *
 * CONVENTIONS come from the #1 Context Snapshot, not from this skill's defaults:
 * CSF 3, title `Components/<ComponentName>`, `autodocs: false`, `tags: []`. The
 * repository declares no global decorators and no autodocs tag, so none is added here.
 * Input is the FIRST component story in this repository — #1 recorded the
 * `Components/` group as declared-but-unattested, and this file is what attests it.
 */

const meta = {
  title: 'Components/Input',
  component: Input,
  parameters: {
    layout: 'padded',
  },
  argTypes: {
    label: { control: 'text' },
    placeholder: { control: 'text' },
    description: { control: 'text' },
    error: { control: 'text' },
    value: { control: 'text' },
    defaultValue: { control: 'text' },
    required: { control: 'boolean' },
    disabled: { control: 'boolean' },
    size: { control: 'inline-radio', options: ['sm', 'md'] },
    className: { control: false },
    onValueChange: { action: 'valueChange' },
  },
  args: {
    label: 'Email address',
  },
} satisfies Meta<typeof Input>;

export default meta;
type Story = StoryObj<typeof meta>;

/** The canonical configuration: a label and a field, nothing else. */
export const Default: Story = {};

/* -------------------------------------------------------------------------- */
/* Content — CR-003, CR-004, CR-005                                            */
/* -------------------------------------------------------------------------- */

/** CR-004 / AC4 — supporting text below the field, referenced by `aria-describedby`. */
export const WithSupportingText: Story = {
  args: {
    description: 'We only use this to send you receipts.',
  },
};

/** CR-003 / AC3 — the placeholder is visible only while the field is empty. */
export const WithPlaceholder: Story = {
  args: {
    placeholder: 'you@example.com',
  },
};

/**
 * CR-005 / AC5 — the marker is a decorative glyph, `aria-hidden`, so the accessible
 * name stays "Email address" rather than "Email address asterisk". The programmatic
 * required state comes from the native attribute alone (D8).
 */
export const Required: Story = {
  args: {
    required: true,
    description: 'Required to create your account.',
  },
};

/* -------------------------------------------------------------------------- */
/* States — the spec's States table                                            */
/* -------------------------------------------------------------------------- */

/**
 * CR-007 / AC7 — the error REPLACES the supporting text rather than sitting beside it,
 * in one node with a stable id. Set both props here to show the replacement: only the
 * error renders.
 */
export const Error: Story = {
  args: {
    description: 'We only use this to send you receipts.',
    error: 'Enter a valid email address.',
    defaultValue: 'not-an-email',
  },
};

/** CR-009 — not editable, not focusable, skipped by Tab, and no hover treatment. */
export const Disabled: Story = {
  args: {
    disabled: true,
    defaultValue: 'locked@example.com',
    description: 'Locked while the form is submitting.',
  },
};

/**
 * The spec's error + disabled row: the disabled appearance wins, and the error message
 * is STILL rendered. A server-rejected value the user cannot currently edit is real.
 */
export const ErrorAndDisabled: Story = {
  args: {
    disabled: true,
    defaultValue: 'taken@example.com',
    error: 'That address is already registered.',
  },
};

/* -------------------------------------------------------------------------- */
/* Sizes — CR-012, CR-013                                                      */
/* -------------------------------------------------------------------------- */

/** `md`, 40px via `--ds-shared-height-md`. The default. */
export const Medium: Story = {
  args: { size: 'md', description: '40px — the regular size, for standard forms.' },
};

/** `sm`, 34px via `--ds-shared-height-sm`. Compact, for table filter bars and cells. */
export const Small: Story = {
  args: { size: 'sm', description: '34px — compact, for dense layouts.' },
};

/* -------------------------------------------------------------------------- */
/* Edge cases — only the categories the spec marks `covered`                    */
/* -------------------------------------------------------------------------- */

/**
 * `empty` — an empty value shows the placeholder if one is set and nothing otherwise.
 * An empty string is a legitimate value and is never coerced to `undefined`.
 */
export const Empty: Story = {
  args: { defaultValue: '' },
};

/**
 * `long_content` — a long label wraps to as many lines as it needs and the field does
 * not move up to meet it; a long error wraps and the block grows. Nothing truncates.
 */
export const LongContent: Story = {
  args: {
    label:
      'Email address we should use for billing receipts, delivery notifications and account recovery',
    defaultValue:
      'a-very-long-email-address-that-scrolls-horizontally@an-unusually-long-domain.example.com',
    error:
      'That address is already registered to another account. Sign in instead, or use a different address — if you believe this is a mistake, contact support and quote reference 4471.',
  },
  decorators: [
    (StoryFn) => (
      <div className="max-w-xs">
        <StoryFn />
      </div>
    ),
  ],
};

/**
 * `mobile` — the field is fluid and fills its container at both sizes. No fixed width is
 * set anywhere, so the container owns width; height is unaffected by viewport.
 */
export const Mobile: Story = {
  args: { description: 'The container owns the width. The field fills it.' },
  decorators: [
    (StoryFn) => (
      <div className="max-w-xs">
        <StoryFn />
      </div>
    ),
  ],
};

/* -------------------------------------------------------------------------- */
/* Value ownership — CR-010                                                    */
/* -------------------------------------------------------------------------- */

/**
 * Uncontrolled: `defaultValue` seeds the field and the component owns the value
 * thereafter. `onValueChange` still fires on every edit.
 */
export const Uncontrolled: Story = {
  args: {
    defaultValue: 'seeded@example.com',
    description: 'The component owns this value. Type to change it.',
  },
};

/**
 * Controlled: `value` is supplied and the component never stores its own. This story
 * deliberately does NOT write the value back, so typing does nothing — which is the
 * honest demonstration of what "controlled" means, rather than a wired-up example that
 * looks identical to the uncontrolled one.
 */
export const Controlled: Story = {
  args: {
    value: 'fixed@example.com',
    description: 'The consumer owns this value and is not updating it, so typing is inert.',
  },
};

/* -------------------------------------------------------------------------- */
/* Interaction — the spec's accessibility contract (#6 authors, #7 evaluates)   */
/* -------------------------------------------------------------------------- */

/**
 * A11Y-001 / CR-002 — clicking the label moves focus into the field. Native
 * `<label for>` behaviour, not a click handler.
 */
export const LabelActivatesField: Story = {
  args: { description: 'Click the label — the caret lands in the field.' },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);

    await userEvent.click(canvas.getByText('Email address'));

    await expect(canvas.getByRole('textbox')).toHaveFocus();
  },
};

/**
 * A11Y-006 / A11Y-008 — Tab in, Tab out, no key handling of the component's own. Focus
 * is visible from the keyboard route as well as the pointer route, which is why the
 * component uses `focus:` rather than `focus-visible:` (CR-006).
 */
export const Keyboard: Story = {
  args: { description: 'Tab in, type, Tab out.' },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const field = canvas.getByRole('textbox');

    await userEvent.tab();
    await expect(field).toHaveFocus();

    await userEvent.type(field, 'typed@example.com');
    await expect(field).toHaveValue('typed@example.com');

    await userEvent.tab();
    await expect(field).not.toHaveFocus();
  },
};

/**
 * A11Y-007 / CR-009 — a disabled field is removed from the tab order by the native
 * attribute. `aria-disabled` is deliberately not used: it would leave the field
 * focusable, which is the opposite of the requirement.
 */
export const DisabledSkippedByTab: Story = {
  render: (args) => (
    <div className="flex flex-col gap-4">
      <button type="button" data-testid="before">
        Before
      </button>
      <Input {...args} />
      <button type="button" data-testid="after">
        After
      </button>
    </div>
  ),
  args: {
    disabled: true,
    description: 'Tab from "Before" — focus lands on "After", never on the field.',
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);

    canvas.getByTestId('before').focus();
    await userEvent.tab();

    await expect(canvas.getByTestId('after')).toHaveFocus();
  },
};

/**
 * A11Y-004 / A11Y-008 — focused while in error. The border keeps the error token and
 * the 2px ring is added in the SAME token, so focus is carried by the ring's presence
 * rather than by a second hue (D3). There is no live region: `aria-invalid` plus
 * `aria-describedby` make the message reachable without interrupting (D7).
 */
export const ErrorAndFocus: Story = {
  args: {
    error: 'Enter a valid email address.',
    defaultValue: 'not-an-email',
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const field = canvas.getByRole('textbox');

    field.focus();

    await expect(field).toHaveFocus();
    await expect(field).toHaveAttribute('aria-invalid', 'true');
    await expect(canvas.queryByRole('alert')).not.toBeInTheDocument();
  },
};

/* -------------------------------------------------------------------------- */
/* Playground                                                                  */
/* -------------------------------------------------------------------------- */

/**
 * Every public prop, wired to a control. `className` is deliberately not controllable:
 * it is a styling hook for a call site, not a value to explore interactively.
 */
export const Playground: Story = {
  args: {
    label: 'Email address',
    placeholder: 'you@example.com',
    description: 'We only use this to send you receipts.',
    required: false,
    disabled: false,
    size: 'md',
  },
};
